### ISSUE TITLE
update ish to stream and other issues

### ISSUE THREAD

**Issue by bbakernoaa** [noaa-oar-arl/monetio#106]
Several updates are needed for the ISH reader. 

- The current reader force downloads the data.  This isn't ideal as the database can be quite large.  
- There currently is not a parallel way to download / process the data
- The methods to select regions based on latlon box, state or country did not work
- Visibility isn't added under the `_clean_columns_by_name` routine in `_clean`
- Can't process outside of a single year

**Comment by zmoon** [comment]
Fixed in `develop`
