### ISSUE TITLE
pardump.py improvements needed

### ISSUE THREAD

**Issue by amcz** [noaa-oar-arl/monetio#13]
1.  pardump.py write method should be able to take as input a pandas DataFrame.
2.  Currently the filename is added as a key to the DataFrame.  There should be a better way to keep this information in the DataFrame.

**Comment by bbakernoaa** [comment]
@amcz has there been any progress on this?

**Comment by zmoon** [comment]
Using the `.attrs` dict is a possible solution.

**Comment by amcz** [comment]
These functionalities no longer needed.
