### ISSUE TITLE
ish.py not finding old_div function

### ISSUE THREAD

**Issue by amcz** [noaa-oar-arl/monetio#18]
On master branch using ish.py.
not finding old_div function. 

 File "/lib/python3.8/site-packages/monetio/obs/ish.py", line 139, in _clean_column
    return old_div(series, multiplier)
NameError: name 'old_div' is not defined

**Comment by bbakernoaa** [comment]
I believe this just needs to be changed so that the division is done.  This is legacy from the python 2 to 3 conversion which we are just python 3 now.

**Comment by zmoon** [comment]
Fixed by b416e62
