### ISSUE TITLE
convert hysplit output for processing in Met3D?

### ISSUE THREAD

**Issue by Marcel0Meyer** [noaa-oar-arl/monetio#20]
Hi,
we are thinking about writing some python scripts to convert Hysplit output such that it can be loaded and visually analysed in Met3D. Happy to discuss this further...
Marcel

**Comment by bbakernoaa** [comment]
@Marcel0Meyer I'd be happy to include a function to convert a MONETIO formated object to a format the Met3D could read.  From what I can tell this could be done for more than just hysplit output but also for Eulerian gridded models such as composition or weather.  This could be really interesting for upcoming projects NOAA ARL is involved in with fires @dtonggmu  @drnimbusrain 

@Marcel0Meyer Do you already have something that did this (even if it was hard coded) it may help to speed up development of this.

**Comment by Marcel0Meyer** [comment]
yes, I have two small python scripts which I wrote during the workshop this week. These convert the PARDUMP and the cdump hysplit output into a netcdf file formatted for loading into Met3D. Let me have another look at them and then I ll send them through. Met3D was developed for visualizing 3D gridded data including ensemble support. So, yes, other Eularian grid outputs and NWP data can be analysed with it. For example, it can read the ECMWF data. All the visualization routines are GPU based so its pretty quick / interactive rates also for larger files. If you are interested, checkout: 
https://met3d.wavestoweather.de/met-3d.html
https://gitlab.com/wxmetvis/met.3d

**Comment by Marcel0Meyer** [comment]
It would be great if you include a function to convert Monetio object for processing in Met3D. I have to admit, I was not aware of MONETIO before you told me about it. Is it used for research purposes at ARL and/or more widely? Curious to hear more about these projects involving fires..

**Comment by bbakernoaa** [comment]
Yes right now MONET is primarily used within ARL but it is publicly available for the last few years. I originally developed it to revaluation the National Air Quality Forecast which our lab does the development for. It has expanded and is now being included with Hysplit and to evaluate other NOAA Air composition models. 

MONETIO and MONET could be used to evaluate other composition models fairly easily as well. For instance, it could be used with WRF-Chem.

**Comment by Marcel0Meyer** [comment]
Hi, 
any news on the MOETIO - Met3D interface? Let me know if I can help with Met3D specific info or so..
Marcel

**Comment by bbakernoaa** [comment]
Sorry I got tied up on others things. I’ll upload the branch I have so you
can take a look after lunch.

**Comment by Marcel0Meyer** [comment]
that's great. No hurry, I am in Hamburg and its already evening here so will go home for today, but will have a look tomorrow.

**Comment by bbakernoaa** [comment]
@Marcel0Meyer I've uploaded what I've done so far in the met3dnc branch.  I just included an xarray accessor into the __init__.py file so that it could be a little more general between datasets.  We still need to work out pressure it in but, for an initial go, I think we are on the way.  

example usage: 

```python
import monetio as mio
cdump = mio.hysplit.open_dataset('CDUMP_FILENAME')

cdump.monetio.to_met3d_nc(filename='output_met3d_filename.nc')
```

**Comment by Marcel0Meyer** [comment]
Excellent. Thanks. I will need to have a closer look and talk to Marc and then come back to you...

**Comment by Marcel0Meyer** [comment]
What do you think would be the best way to integrate required format for the vertical coordinates into Monetio? 

As I dont know much about Monetio, I thought it makes sense to summarize to you the requirements of Met3D and provide you with some more examples of data files / data format required by Met3D so that we can think about useful next steps 
(see attached notes and new files in the Dropbox Folder: Hysplit_Met3D).

[VerticalCoordinates_HysplitMet3DInterface_Examples.txt](https://github.com/noaa-oar-arl/monetio/files/4878529/VerticalCoordinates_HysplitMet3DInterface_Examples.txt)

We just need to provide the vertical coordinates in one of the 3 formats/types required by Met3D (see attached notes). Ideally, I guess, we could include an option into the method in Monetio which allows specifying the format of the vertical coordinate in the Met3D output depending on the type of information that is available in the data. For example, if we have pressure level data, we can simply write an ncfile in the format of that minimal example, I sent to you. Or, in a different case, if you have data on some model level as well as a 3D pressure field, then one could choose to output the required format for data on generalized model levels with auxiliary pressure field. 

What do you think? Do you need any other examples or so?

**Comment by bbakernoaa** [comment]
@Marcel0Meyer I would like to keep the conversion tool kinda vanilla. I know we need to provide a vertical coordinate but It may be something that we advise the user to do.  We could include some conversions between common vertical coordinates, ie height agl, asl, pressure, sigma-p, etc. This could be very useful outside of this function as well.

What I'm worried about is some models put variables in different files. For example, CMAQ puts all chemical output species in a single file while pressure and height exist as a separate variable. 

MONET does include a generic function to interpolate to a given vertical level/levels if given the vertical coordinate. 

What do you think about having a check to see if there is a vertical coordinate (z) or (lev) in the file.  If not assign a constant pressure level with a kwarg (default 1000mb or something)?

**Comment by Marcel0Meyer** [comment]
Sure, agreed, that it would be ideal to have the flexibility. I was looking at it more from a case-specific perspective: a kind of simple conversion tool, which would be able to convert the standard Hysplit output (cdump, pardump, deposition) into an ncfile in a format that Met3D likes. But if we could also use it for other models, like CMAQ, that would of course be even better. 

I have never worked with CMAQ, and I am not sure if I understand your question about different files. The info about the vertical coordinate can be in a separate file, thats totally fine for Met3D. It scans all files in a given directory. We would just need to make sure that Met3D can relate the two. In order for that to work, one way would be that the vertical dimension of the chemical output variable needs to match the one in the pressure field. See last example (3) at the bottom of these notes I sent earlier today.

If you happen to have a simple example CMAQ default output - like some pollutant air-concentration with the vertical coordinate information as a separate file, then I can try loading it into Met3D as-is. If the data comes on some vertical level and there is a 3D pressure field on these levels as well, then we should be able to directly load the data without any change. If not, we can continue from there?

Met3D has some default checks for vertical coordinates in its data reading methods. If there is no vertical coordinate, then it will interpret the data as 2-Dimensional, or crash. So we can read deposition fields or any 2D gridded field directly, as long as it is on a regular lat-lon grid. I like the idea of checking for the existence of a vertical coordinate. From our perspective it would not be necessary that the vertical coordinate info is written in the same file as the variable of interest (e.g. a pollutant), so maybe, as an alternative approach, we could check all files in a folder or define the name of the file with the vertical information and then check if the vertical information is provided in a format that Met3D can read.

Converting between height (m agl, m asl) and pressure would definitely be useful I think. 

Do you know if Hysplit can output tracer concentration data on pressure levels?

**Comment by amcz** [comment]
HYSPLIT will not output concentrations on pressure levels. vertical coordinate is either meters above ground level or 
meters above mean sea level.

**Comment by Marcel0Meyer** [comment]
ok, thanks for the information. In that case a simple conversion from meters above ground level or meters above sea level to pressure would be needed.

**Comment by amcz** [comment]
Have you tried the current reader for cdump files in MONETIO? It outputs an xarray object. You would simply need to apply the conversion to pressure  to the z axis.

**Comment by Marcel0Meyer** [comment]
Hi, i have not tried the current cdump reader, no, but I wrote a minimal python script to read the cdump.txt output and converted the vertical coordinate to pressure assuming a standard atmosphere. That works fine.

**Comment by Marcel0Meyer** [comment]
Hi, just wanted to say that there is in option in Met3D for converting geometric height in meters to pressure levels using the ICAO atmosphere. We usually dont use it for detailed analysis, because of the approximations implied by assuming a standard atmosphere for conversion, but as a simple way for 3-D visual analysis of data with vertical coordinates in meters, it may be useful.

**Comment by bbakernoaa** [comment]
I haven't seen any movement on this.  I'm going to close it unless someone speaks up
