### ISSUE TITLE
Update attributes in dataset returned from hysplit.py

### ISSUE THREAD

**Issue by amcz** [noaa-oar-arl/monetio#35]
Currently the attributes make it difficult to write to netcdf. 
The following attributes need to be updated.
Species ID
Starting Locations
Sampling Time
Source Date

The Concentration Grid attribute was updated in the last commit to hysplit dev. It was a dictionary. Now the concentration grid attribute no longer exists and each entry in that dictionary is its own attribute.

In addition, currently a 'sample time hours' and 'Sampling Time' attribute exists. The 'sample time hours' does not appear to be the correct number, while the 'Sampling Time' is a datetime timedelta object and cannot be written to netcdf.
This should be resolved.

**Comment by aring1988** [comment]
Removed the Sampling Time attribute (it is redundant).
Converted the Source Date attribute to a string with formatting %Y%m%d.%H%M%S.
Changed Starting Locations to Starting Latitudes, Starting Longitudes, and Starting Heights, each a single dimension list - avoids the multidimensional attribute error when creating a netCDF

I do not think there is a need to change Species ID at the moment, no problems when generating netCDF files.

**Comment by zmoon** [comment]
It seems this was fixed by #37, so closing for now.
