### ISSUE TITLE
I installed all the libraries required (by command: pip install .) in a new environment. I had no issues while installing. But, when importing the library, I am getting the following error

### ISSUE THREAD

**Issue by praful-dodda** [noaa-oar-arl/monetio#38]
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-7087af746425> in <module>
----> 1 import monetio as mio
      2 import numpy as np
      3 import pandas as pd
      4 import matplotlib.pyplot as plt
      5 import seaborn as sns       # better color palettes

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/monetio/__init__.py in <module>
----> 1 from . import grids, models, obs, profile, sat
      2 
      3 # point observations
      4 airnow = obs.airnow
      5 aeronet = obs.aeronet

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/monetio/obs/__init__.py in <module>
----> 1 from . import (aeronet, airnow, aqs, cems_mod, crn, epa_util, icartt,
      2                improve_mod, ish, ish_lite, nadp, openaq)
      3 
      4 __all__ = [
      5     'aeronet', 'airnow', 'aqs', 'crn', 'epa_util', 'improve_mod', 'ish', 'ish_lite'

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/monetio/obs/aqs.py in <module>
      5 
      6 import pandas as pd
----> 7 from dask.diagnostics import ProgressBar
      8 
      9 from .epa_util import read_monitor_file

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/dask/__init__.py in <module>
      1 from . import config, datasets
      2 from ._version import get_versions
----> 3 from .base import annotate, compute, is_dask_collection, optimize, persist, visualize
      4 from .core import istask
      5 from .delayed import delayed

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/dask/base.py in <module>
     14 from typing import Iterator, Mapping, Set
     15 
---> 16 from tlz import curry, groupby, identity, merge
     17 from tlz.functoolz import Compose
     18 

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/tlz/_build_tlz.py in exec_module(self, module)
     52 
     53     def exec_module(self, module):
---> 54         toolz_mods = self._load_toolz(module.__name__)
     55         fast_mod = toolz_mods.get('cytoolz') or toolz_mods['toolz']
     56         slow_mod = toolz_mods.get('toolz') or toolz_mods['cytoolz']

~/anaconda3/envs/cmaq_post/lib/python3.8/site-packages/tlz/_build_tlz.py in _load_toolz(self, fullname)
     26             pass
     27         if not rv:
---> 28             raise ImportError(fullname)
     29         return rv
     30 

ImportError: tlz.curry

**Comment by zmoon** [comment]
Hi @praful-dodda, did you resolve this? This isn't a `monetio` issue, but a `dask` issue where it is failing to load `toolz.curry`. Before [this Dask release](https://docs.dask.org/en/stable/changelog.html#v2021-03-1), `toolz` was an optional dependency, so maybe you were just missing it.
