### ISSUE TITLE
GEOMS file format reader

### ISSUE THREAD

**Issue by bbakernoaa** [noaa-oar-arl/monetio#50]
Several lidar networks use the GEOMS file format to store their data.  It would be beneficial for MONETIO to include this file format for ingest and model comparisons.  

More information on the GEOMS file format can be found here: https://evdc.esa.int/documentation/geoms/#:~:text=GEOMS%20documentation,reporting%20of%20data%20and%20metadata.

**Comment by zmoon** [comment]
I think it will also be useful to check against what `h4tonccf_nc4` does with our sample file.

https://www.hdfeos.org/software/h4cflib.php

**Comment by bbakernoaa** [comment]
@zmoon I used this utility initially to open the file with xarray.  it partially worked but I was at least able to open It

**Comment by zmoon** [comment]
Going to close this for now, since #57 did add reader for TOLNet GEOMS format at that time, though would need more work to generalize for other GEOMS datasets I assume.
