### ISSUE TITLE
EPA AQS URLs causing error

### ISSUE THREAD

**Issue by zmoon** [noaa-oar-arl/monetio#90]
* EPA AQS URLs erroring in link check [apparently](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled) due to their server not supporting OpenSSL 3 client
  - e.g.  
    ```(tutorial/aqs_pams: line   27) broken    https://aqs.epa.gov/aqsweb/airdata/download_files.html - HTTPSConnectionPool(host='aqs.epa.gov', port=443): Max retries exceeded with url: /aqsweb/airdata/download_files.html (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)')))```
  - seems this is affecting the AQS test as well (232e0e4):
    `FAILED tests/test_aqs.py::test_aqs - requests.exceptions.SSLError: HTTPSConnectionPool(host='aqs.epa.gov', port=443): Max retries exceeded with url: /aqsweb/airdata/daily_PM10SPEC_2019.zip (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)')))`

_Originally posted by @zmoon in https://github.com/noaa-oar-arl/monetio/issues/85#issuecomment-1290904269_

**Comment by zmoon** [comment]
Some more info [here](https://stackoverflow.com/a/71646353)

**Comment by zmoon** [comment]
Pinning `openssl` is an option I suppose (`1.1.1q` is the current < 3 release)

**Comment by zmoon** [comment]
Also for `requests.get` could try [this method](https://stackoverflow.com/a/73519818)

**Comment by bbakernoaa** [comment]
@zmoon is this finished?

**Comment by zmoon** [comment]
Still working around it in CI. AFAIK as I know the situation hasn't changed. Did you have any luck contacting them about it?

**Comment by zmoon** [comment]
Just tested this locally, `aqs.epa.gov` URLs still have the same issue in link check and the test when using OpenSSL v3.

**Comment by zmoon** [comment]
In CI run for #125 today, the AQS test didn't fail with OpenSSL 3.1.2.

**Comment by bbakernoaa** [comment]
That’s great!

**Comment by zmoon** [comment]
Phil Dickerson from EPA says the server is officially fixed as of last week.

Will keep this issue open until PR removing the related extra CI cases etc.
